test_press	:	test_press.o
	gcc -O1 -o $@ $^ -L../libxlog -lxlog -lpthread -Wl,-rpath ../libxlog

.c.o	:
	gcc -O1 -pg -Wall -D_GNU_SOURCE -o $@ -c $< -I. -I../libxlog

clean	:
	rm -f test_press press.log*
