exe = 		\
	test_conf	\
	test_filemv	\
	test_hashtable	\
	test_hello	\
	test_hex	\
	test_init	\
	test_level	\
	test_mdc	\
	test_press	\
	test_printf	\
	test_syslog	\
	test_syslog_press \
	test_default

.PHONY : clean all

all     :       $(exe)

$(exe)  :       %:%.o
	gcc -O1 -g -o $@ $^ -L../libzlog/.libs -lzlog -lpthread -Wl,-rpath ../libzlog/.libs

.c.o	:
	gcc -O1 -g -pg -Wall -D_GNU_SOURCE -o $@ -c $< -I. -I../libzlog

clean	:
	rm -f press.log* *.o $(exe)
