test_press	:	test_press.o
	gcc -O1 -g -o $@ $^ -L../libzlog/.libs -lzlog -lpthread -Wl,-rpath ../libzlog/.libs

.c.o	:
	gcc -O1 -g -pg -Wall -D_GNU_SOURCE -o $@ -c $< -I. -I../libzlog

clean	:
	rm -f test_press press.log*
