all_o	=		\
	buf.o		\
	category.o	\
	conf.o		\
	event.o		\
	format.o	\
	mdc.o		\
	level.o	\
	rotater.o	\
	rule.o		\
	spec.o		\
	thread.o	\
	zlog.o		\
	zc_arraylist.o	\
	zc_profile.o	\
	zc_hashtable.o	\
	zc_util.o	\
	zc_xplatform.o

all	:	libzlog.so

libzlog.so	:	$(all_o)
	gcc -shared -o $@ $(all_o) -lpthread

.c.o	:
	gcc -g -Wall -Werror -D_GNU_SOURCE -fPIC -o $@ -c $< -I.
#-Werror

clean	:
	-rm -f libzlog.so $(all_o)
