all_o	=		\
	buf.o		\
	category.o	\
	conf.o		\
	event.o		\
	format.o	\
	mdc.o		\
	priority.o	\
	rotater.o	\
	rule.o		\
	spec.o		\
	thread.o	\
	xlog.o		\
	zc_arraylist.o	\
	zc_error.o	\
	zc_hashtable.o	\
	zc_util.o	\
	zc_xplatform.o

all	:	libxlog.so

libxlog.so	:	$(all_o)
	gcc -shared -o $@ $(all_o) -lpthread

.c.o	:
	gcc -g -Wall -Wwrite-strings -D_GNU_SOURCE -fPIC -o $@ -c $< -I.
#-Werror

clean	:
	-rm -f libxlog.so $(all_o)
